# Generated by Django 4.1.5 on 2023-01-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='image',
            field=models.ImageField(default='./background.jpg', upload_to=''),
        ),
    ]
